import ../anon_handler/app as a0
import ../basic_auth/app as a1
import ../basic_cookies/app as a2
import ../basic_crud/app as a3
import ../blog/app as a4
import ../cors/app as a5
import ../csrf/app as a6
import ../dsl_routes/app as a7
import ../group_routes/app as a8
import ../headers/app as a9
import ../helloworld/app as a10
import ../http_server/app as a11
import ../http_server_custom_settings/app as a12
import ../http_server_dotenv/app as a13
import ../http_static_server/app as a14
import ../karax_template/app as a15
import ../middleware_basic/app as a16
import ../middleware_before_after/app as a17
import ../nwt_template/app as a18
import ../regex_url/app as a19
import ../request/app as a20
import ../response/app as a21
import ../signed_cookie_session/app as a22
import ../todoapp/app as a23
import ../url_param/app as a24
import ../url_query/app as a25
import ../basic/app as a26
import ../basicconf/app as a27
import ../memorysession/app as a28
import ../redissession/app as a29
import ../signedcookiesession/app as a30
import ../todolist/app as a31
import ../websocket/app as a32
